import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>burn baby, burn... 🔥</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          burn baby, burn... 🔥
        </h1>

        <p className={styles.description}>
          this website will track things being burned in the ethereum world
        </p>

        <div className={styles.grid}>
          <div onClick={() => router.push('/zero_address')} className={styles.card}>
            <h2>Zero address</h2>
            <p>0x0000000000000000000000000000000000000000</p>
          </div>
          <div onClick={() => router.push('/dead_address_1')} className={styles.card}>
            <h2>Dead address</h2>
            <p>0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddead</p>
          </div>
          <div onClick={() => router.push('/dead_address_2')} className={styles.card}>
            <h2>Dead address</h2>
            <p>0x000000000000000000000000000000000000dead</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
          created by mehran with love
      </footer>
    </div>
  )
}
