import { useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  const [address, setAddress] = useState('')
  
  const handleChange = (e) => {
    e.preventDefault()
    setAddress(e.target.value)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>finder, find away... 🔥</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          finder, find away... 🔥
        </h1>

        <p className={styles.description}>
          this website will help you search balances quickly
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>enter address</h2>
            <input
              type='text'
              value={address}
              onChange={handleChange}
              className={styles.input}
            />
            <div
              className={styles.button}
              onClick={() => router.push(`/balance/${address}`)}
            >
              Query
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
          created by mehran ✨✨✨
      </footer>
    </div>
  )
}
